# Jungfernstieg Configuration Example
# Copy this file to config.yaml and modify as needed

# System Configuration
system:
  name: "jungfernstieg-main"
  version: "0.1.0"
  environment: "development"  # development, testing, production
  
# Safety Configuration
safety:
  biological_safety_level: "BSL-2+"
  neural_viability_threshold: 95.0  # Minimum viable percentage
  emergency_response_time: 0.1  # Maximum emergency response time (seconds)
  monitoring_interval: 1.0  # Safety monitoring interval (seconds)
  
  # Emergency contacts
  emergency_contacts:
    primary: "emergency@research.institute"
    secondary: "backup@research.institute"
    emergency_phone: "+1-XXX-XXX-XXXX"

# Biological Neural Networks
biological:
  neural_networks:
    - name: "primary_cortical"
      type: "primary_cortical"
      size: "medium"
      culture_duration: 14  # days
      
    - name: "hippocampal"
      type: "hippocampal" 
      size: "small"
      culture_duration: 10  # days
  
  # Neural interface configuration
  interfaces:
    microelectrode_arrays: true
    optical_stimulation: false
    chemical_perfusion: true
    electrical_stimulation: false
  
  # Monitoring configuration
  monitoring:
    immune_cells: true
    memory_cells: true
    viability_sensors: true
    activity_monitoring: true

# Virtual Blood System
virtual_blood:
  # Composition (concentrations in appropriate units)
  composition:
    dissolved_oxygen: 15.0      # mg/L
    glucose: 1.0                # g/L
    amino_acids: 0.5            # g/L
    lipids: 0.2                 # g/L
    sodium: 140.0               # mmol/L
    potassium: 5.0              # mmol/L
    calcium: 2.5                # mmol/L
    neurotransmitters: 0.001    # g/L
    growth_factors: 0.0001      # g/L
  
  # Circulation parameters
  circulation:
    target_flow_rate: 8.5       # mL/min
    target_pressure: 45.0       # mmHg
    temperature: 37.0           # °C
    ph: 7.4
  
  # Filtration settings
  filtration:
    efficiency_target: 95.0     # %
    waste_removal_rate: 90.0    # %
    purification_cycles: 3

# Oscillatory Virtual Machine
oscillatory_vm:
  # Heart function configuration
  heart:
    resting_rate: 60.0          # BPM equivalent
    active_rate: 80.0           # BPM equivalent
    processing_rate: 100.0      # BPM equivalent
    emergency_rate: 120.0       # BPM equivalent
  
  # S-entropy engine
  s_entropy:
    navigation_precision: 1e-12
    coordinate_cache_size: 10000
    optimization_enabled: true
  
  # Virtual processor foundry
  processors:
    max_processors: 1000
    default_architecture: "quantum"
    creation_timeout: 1e-15     # seconds (femtosecond lifecycle)
  
  # Temporal coordination
  temporal:
    base_precision: 1e-30       # seconds
    enhancement_enabled: true
    recursive_improvement: true

# Consciousness Integration
consciousness:
  # Internal voice configuration
  internal_voice:
    mode: "responsive"          # passive, responsive, collaborative, advisory
    naturalness_target: "seamless"  # mechanical, functional, natural, seamless
    response_latency: 0.05      # seconds
  
  # Context understanding
  context:
    environmental_depth: "comprehensive"
    biological_integration: true
    social_awareness: true
    emotional_intelligence: true
  
  # Thought integration
  thought_integration:
    seamless_flow: true
    interruption_avoidance: true
    natural_timing: true

# Environmental Sensing
sensors:
  # Acoustic sensors (Heihachi)
  acoustic:
    enabled: true
    sampling_rate: 44100        # Hz
    emotion_detection: true
    social_context: true
    fire_protocol: true
  
  # Visual sensors (Hugure)
  visual:
    enabled: true
    resolution: "1920x1080"
    frame_rate: 30              # FPS
    object_recognition: true
    scene_analysis: true
  
  # Biological sensors (Gospel)
  biological:
    enabled: true
    genomic_analysis: true
    health_monitoring: true
    metabolic_tracking: true
  
  # Environmental sensors
  environmental:
    enabled: true
    atmospheric_monitoring: true
    air_quality: true
    temperature_humidity: true
  
  # Spatial sensors
  spatial:
    enabled: true
    gps_enabled: false          # Set to true if GPS available
    indoor_positioning: true
    movement_tracking: true
  
  # Biomechanical sensors
  biomechanical:
    enabled: false              # Set to true if wearable devices available
    heart_rate: false
    blood_pressure: false
    activity_tracking: false

# Monitoring Configuration
monitoring:
  level: "comprehensive"        # minimal, standard, detailed, comprehensive, diagnostic
  
  # Monitoring intervals (seconds)
  intervals:
    neural_viability: 1.0       # Critical - high frequency
    virtual_blood: 1.0          # Critical - high frequency  
    safety: 0.5                 # Critical - highest frequency
    consciousness: 2.0          # Important
    performance: 5.0            # Standard
    system_health: 10.0         # Overview
  
  # Data retention
  data_retention:
    hours: 24                   # Hours of data to keep
    max_points_per_component: 1000
  
  # Alerting
  alerts:
    neural_viability_critical: 90.0  # %
    virtual_blood_critical: 0.8      # Quality score
    response_time_critical: 0.1      # seconds
    email_alerts: false              # Set to true with SMTP config
    log_alerts: true

# Logging Configuration
logging:
  level: "INFO"                 # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Log files
  files:
    main: "jungfernstieg_system.log"
    safety: "jungfernstieg_safety.log"
    biological: "jungfernstieg_biological.log"
    monitoring: "jungfernstieg_monitoring.log"
  
  # Log rotation
  rotation:
    max_bytes: 10485760         # 10MB
    backup_count: 5

# Development/Testing Configuration
development:
  mock_hardware: true           # Use mock hardware interfaces
  simulate_sensors: true        # Simulate sensor data
  accelerated_time: false       # Accelerate time for testing
  debug_mode: false             # Enable debug features
  
  # Test configuration
  testing:
    neural_tissue_simulation: true
    virtual_blood_simulation: true
    consciousness_simulation: true
    safety_simulation: true

# Production Configuration (use with caution)
production:
  real_hardware: false          # ONLY set to true with real hardware
  live_neural_tissue: false    # ONLY set to true with actual tissue
  emergency_protocols: true    # Always true in production
  backup_systems: true         # Always true in production
  redundant_monitoring: true   # Always true in production
  
  # Compliance
  regulatory_compliance:
    institutional_approval: false  # Set to true when approved
    ethics_approval: false         # Set to true when approved
    safety_certification: false   # Set to true when certified

# Memorial Configuration
memorial:
  # Saint Stella-Lorraine Masunda dedication
  stella_lorraine_masunda:
    enabled: true
    memorial_frequency: "continuous"
    precision_enhancement: true
    mathematical_validation: true
    eternal_coordinates: true